import { ShimmerButton } from "@/components/ui/shimmer-button";

const faq = [
  {
    question: "Is Ad Forge a CRM?",
    answer:
      "No. Ad Forge is a specialized AI-powered suite for brand creation and marketing assets. It can integrate with your existing CRM, but it doesn’t replace it.",
  },
  {
    question: "Which platforms does Ad Forge support?",
    answer:
      "Our initial launch focuses on the most popular platforms for modern brands, including Instagram, TikTok, Facebook, YouTube, and LinkedIn. Support for X (formerly Twitter) and Pinterest will follow based on user feedback.",
  },
  {
    question: "Do I own the content generated by Ad Forge?",
    answer:
      "Yes. Any content, brand assets, or strategies generated through Ad Forge are 100% your intellectual property. You own everything you create.",
  },
  {
    question: "Is there human support, or is it all AI?",
    answer:
      "Absolutely. While the platform is AI-driven, our customer success team is here to help. Premium tiers will also have access to dedicated brand strategists.",
  },
  {
    question: "When will early access go live?",
    answer:
      "We’re planning to roll out early access in Q4 of this year. Everyone on the waitlist will be notified as soon as we’re ready and will receive an exclusive invitation to join.",
  },
];

export default function WaitlistPage() {
  return (
    <div className="bg-[#050505] pt-24 text-white">
      <section className="mx-auto flex max-w-4xl flex-col gap-6 px-6 pb-16 text-center">
        <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
          The future of brand building is here.
        </h1>
        <p className="mx-auto max-w-2xl text-base text-white/70">
          Join the waitlist for Ad Forge and get early access to our AI-powered suite of branding tools for creators and SMBs.
        </p>
      </section>

      <section className="mx-auto max-w-3xl rounded-3xl border border-white/10 bg-black/40 p-10">
        <h2 className="text-2xl font-semibold text-white">
          Join the early access waitlist
        </h2>
        <form className="mt-8 grid gap-6" method="post">
          <div className="grid gap-2">
            <label htmlFor="full-name" className="text-sm font-medium text-white">
              Full name
            </label>
            <input
              id="full-name"
              name="fullName"
              className="rounded-xl border border-white/10 bg-black/60 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-white/30"
              placeholder="Alex Rivera"
              required
            />
          </div>
          <div className="grid gap-2">
            <label htmlFor="work-email" className="text-sm font-medium text-white">
              Work email
            </label>
            <input
              id="work-email"
              type="email"
              name="workEmail"
              className="rounded-xl border border-white/10 bg-black/60 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-white/30"
              placeholder="you@brand.com"
              required
            />
          </div>
          <div className="grid gap-2">
            <label htmlFor="business-type" className="text-sm font-medium text-white">
              Business type
            </label>
            <input
              id="business-type"
              name="businessType"
              className="rounded-xl border border-white/10 bg-black/60 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-white/30"
              placeholder="DTC skincare"
            />
          </div>
          <div className="grid gap-2">
            <label htmlFor="website" className="text-sm font-medium text-white">
              Website / IG handle
            </label>
            <input
              id="website"
              name="website"
              className="rounded-xl border border-white/10 bg-black/60 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-white/30"
              placeholder="adforge.ai or @adforge"
            />
          </div>
          <div className="grid gap-2">
            <label htmlFor="monthly-revenue" className="text-sm font-medium text-white">
              Monthly revenue (USD)
            </label>
            <input
              id="monthly-revenue"
              name="monthlyRevenue"
              className="rounded-xl border border-white/10 bg-black/60 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-white/30"
              placeholder="$15k"
            />
          </div>
          <div className="grid gap-2">
            <label htmlFor="country" className="text-sm font-medium text-white">
              Country
            </label>
            <input
              id="country"
              name="country"
              className="rounded-xl border border-white/10 bg-black/60 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-white/30"
              placeholder="United States"
            />
          </div>
          <div className="grid gap-2">
            <label htmlFor="branding-challenge" className="text-sm font-medium text-white">
              What is your biggest branding challenge?
            </label>
            <textarea
              id="branding-challenge"
              name="brandingChallenge"
              rows={4}
              className="rounded-xl border border-white/10 bg-black/60 px-4 py-3 text-sm text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-white/30"
              placeholder="Tell us where you need the most support"
            />
          </div>
          <div className="flex items-center justify-start">
            <ShimmerButton
              type="submit"
              className="bg-white/90 text-black hover:text-white hover:[background:rgba(255,255,255,0.2)]"
            >
              <span className="text-sm font-medium tracking-tight">
                Join the waitlist
              </span>
            </ShimmerButton>
          </div>
        </form>
      </section>

      <section className="mx-auto max-w-4xl space-y-6 px-6 pb-24 pt-16">
        <h2 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">
          Frequently asked questions
        </h2>
        <p className="max-w-2xl text-base text-white/70">
          Have questions? We have answers.
        </p>
        <div className="space-y-6">
          {faq.map((item) => (
            <div
              key={item.question}
              className="rounded-3xl border border-white/10 bg-black/40 p-6"
            >
              <h3 className="text-xl font-semibold text-white">
                {item.question}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-white/70">
                {item.answer}
              </p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
